# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170304_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
